spring:
  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost:3306/api?createDatabaseIfNotExist=true
    username: root
    password: m0933266
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600 # 5min
    refresh-token-expiration: 604800 # 7d

  flyway:
    enabled: true

